In [1]:
import numpy as np
import scipy.linalg as la

In [3]:
matrix = np.array([[10,6],[2,7]])
matrix

array([[10,  6],
       [ 2,  7]])

In [4]:
type(matrix)

numpy.ndarray

In [5]:
print("Inverse of matrix : ", la.inv(matrix))

Inverse of matrix :  [[ 0.12068966 -0.10344828]
 [-0.03448276  0.17241379]]


In [16]:
matrix = np.array([[4,9],[3,5]])
print(matrix)
print("Determinent of matrix: ", la.det(matrix))


[[4 9]
 [3 5]]
Determinent of matrix:  -6.999999999999999


In [17]:
a = np.array([[0,2,3], [4,5,6], [7,8,9]])
print(a)
la.det(a)

[[0 2 3]
 [4 5 6]
 [7 8 9]]


3.0

In [24]:
# Solving linear equations
# 2x + 3y + z = 21
# -x + 5y + 4z = 9
# 3x + 2y + 9z = 6
coefficients_array = np.array([[2,3,1],[-1,5,4],[3,2,9]])
values_array = np.array([21,9,6])
solution_array = la.solve(coefficients_array, values_array)
print("x = ",round(solution_array[0],2))
print("y = ",round(solution_array[1],2)) # rounding up the values to two decimal places
print("z = ",round(solution_array[2],2))


x =  4.95
y =  4.35
z =  -1.95


In [23]:
4.95*2 + 4.35*3 + -1.95

21.0

In [26]:
from scipy.stats import norm

In [28]:
norm.rvs(loc=0, scale=1, size=10) # rvs for random variables

array([ 2.64121484,  0.8083049 ,  0.40842229,  0.15002562,  0.53635842,
        0.65711659,  0.26772089, -0.16086469, -0.02627547, -0.85055246])

In [29]:
norm.cdf(5, loc=1, scale=2)

0.9772498680518208

In [31]:
norm.pdf(9, loc=0, scale=1)

1.0279773571668917e-18