In [1]:
!python --version

Python 3.8.10


In [2]:
a = 10.1
type(a)

float

In [3]:
q1 = True
type(q1)

bool

In [4]:
integer_x, integer_y = 4, 6

In [6]:
integer_x, integer_y

(4, 6)

In [18]:
x = 3
id(x)


9789024

In [24]:
print("x:", x)
print(id(x))
x = 7
print(id(x))
x += 1
print(id(x)) # ID is the unique ID of the value we are assigning to a variable. Unique ID is a unique memory location.
x = 8
print(id(x))
y = 8 # assigning same value to two different variable results in both variables pointing to same value of ID i.e. same memory location.
print(id(y)) 


x: 8
9789184
9789152
9789184
9789184
9789184


In [25]:
#float to string typcasting
a_float = 45.65
print(a_float)
print(type(a_float))
a_string = str(a_float)
print(a_string)
print(type(a_string))

45.65
<class 'float'>
45.65
<class 'str'>


In [1]:
first_dic = {1:'Abhi', 2:'Yahoo'}
first_dic

{1: 'Abhi', 2: 'Yahoo'}

In [2]:
del first_dic[2]

In [3]:
first_dic

{1: 'Abhi'}

In [1]:
import numpy as np

my_array = np.array([[3,4,5,6,7,9,10],[9,4,3,2,1,3,9]])
my_array

array([[ 3,  4,  5,  6,  7,  9, 10],
       [ 9,  4,  3,  2,  1,  3,  9]])

In [5]:
np.trace(my_array)

7

In [6]:
my_one_d_array = np.array([32,34,456,67,345,456])
print(my_one_d_array)
print(np.transpose(my_one_d_array))

[ 32  34 456  67 345 456]
[ 32  34 456  67 345 456]


In [10]:
my_non_homogeneous_array = np.array([23,34543,54645,34534,434])

In [8]:
my_non_homogeneous_array

array(['2343', '23', '34543', '54645', '34534', '434'], dtype='<U5')

In [11]:
my_non_homogeneous_array*3

array([    69, 103629, 163935, 103602,   1302])

In [13]:
my_non_homogeneous_array.ndim

1

In [16]:
my_non_homogeneous_array.shape

(5,)

In [18]:
my_non_homogeneous_array.dtype

dtype('int64')

In [29]:
my_string_array = np.array([["abcd6656","efgh","klmn"],["fasd","@#$","dsaf"]])

In [30]:
my_string_array.shape

(2, 3)

In [32]:
my_string_array

array([['abcd6656', 'efgh', 'klmn'],
       ['fasd', '@#$', 'dsaf']], dtype='<U8')

In [31]:
my_flatten_string = my_string_array.reshape(6,)
my_flatten_string

array(['abcd6656', 'efgh', 'klmn', 'fasd', '@#$', 'dsaf'], dtype='<U8')

In [7]:
firtst_trial = [10,15,17,26]
second_trial = [12,11,21,24]
np_first_trial = np.array(firtst_trial)
np_second_trial = np.array(second_trial)


In [8]:
total_distance = np_first_trial + np_second_trial # numpy array will add the arrays with +

In [9]:
total_distance

array([22, 26, 38, 50])

In [12]:
firtst_trial + second_trial # list will concatinate with +

[10, 15, 17, 26, 12, 11, 21, 24]

In [13]:
cyclist_trial = np.array([[10,15,17,26],[12,11,21,24]])
first_trial = cyclist_trial[0]
first_trial

array([10, 15, 17, 26])

In [14]:
second_trial = cyclist_trial[1]
second_trial

array([12, 11, 21, 24])

In [15]:
first_cyclist_fisrt_trial = cyclist_trial[0][0] # first element of the first list
first_cyclist_fisrt_trial

10

In [27]:
first_cyclist_all_trial = cyclist_trial[:,3]
first_cyclist_all_trial

array([26, 24])

In [20]:
cyclist_trial.shape

(2, 4)

In [21]:
cyclist_trial

array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [28]:
two_cyclist_trial_data = cyclist_trial[:,1:3] # when using the index range, last index-1 is considered (3 here will be considered as index 2)
two_cyclist_trial_data

array([[15, 17],
       [11, 21]])

In [56]:
cyclist_trial[:,3] # when not using index range, the last index is equal to the actual index 3

array([26, 24])

In [30]:
my_list = ["red", "green", "blue","yellow"]
i = 0
while i < len(my_list):
    print(my_list[i])
    i = i + 1

red
green
blue
yellow


In [31]:
crossed_minimum = cyclist_trial > 20
crossed_minimum

array([[False, False, False,  True],
       [False, False,  True,  True]])

In [32]:
crossed_minimum_trial = cyclist_trial[crossed_minimum]

In [33]:
crossed_minimum_trial

array([26, 21, 24])

In [37]:
print(crossed_minimum_trial.base)

None


In [38]:
crossed_minimum_trial_copy = crossed_minimum_trial.copy()

In [39]:
print(crossed_minimum_trial.base)

None


In [40]:
print(crossed_minimum_trial_copy.base)

None


In [41]:
crossed_minimum_tiral_view = crossed_minimum_trial.view()

In [42]:
print(crossed_minimum_trial.base)

None


In [43]:
print(crossed_minimum_trial_copy.base)

None


In [45]:
print(crossed_minimum_tiral_view.base)

[26 21 24]


In [46]:
np.add(34,45)

79

In [53]:
np.sum([34,5456,6576])

12066