In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([11, 12, 13, 14])
b = np.array([1, 2, 3, 4]) 
c = a - b 
c

array([10, 10, 10, 10])

In [3]:
a = 9/2
b = 5.2/2
print(a, b)

4.5 2.6


In [5]:

series = pd.Series(3,index=['a','b','c'])

In [6]:
series

a    3
b    3
c    3
dtype: int64

In [9]:
a = np.array(1,2,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [8]:
type(a)

numpy.ndarray

In [10]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
AR = np.linspace(5,15,10)

In [12]:
AR.size

10

In [13]:
array = np.array([1,2,3])

In [16]:
x, y, z = np.vsplit(array, 3)

ValueError: vsplit only works on arrays of 2 or more dimensions

In [15]:
print(x, y, z)

[1] [2] [3]
